[package]
name = "ci_util"
version = "0.1.0"
edition = "2021"

[lib]
name = "ci_util"
path = "src/lib.rs"

[profile.release]
lto = "thin"
opt-level = 3

[profile.dev.package."*"]
opt-level = 3

[dependencies]
