[package]
name = "ci_util"
version = "0.1.0"
edition = "2021"

[lib]
name = "ci_util"
path = "src/lib.rs"

[dependencies]
# Last updated 20 nov 2021 based on personal crates and crates.io recent download top 100
aes = "*"
ahash = "*"
aho-corasick = "*"
ammonia = "*"
ansi_term = "*"
anyhow = "*"
approx = "*"
argon2rs = "*"
array_tool = "*"
arrayvec = "*"
async-trait = "*"
atty = "*"
autocfg = "*"
backtrace = "*"
base64 = "*"
bcrypt = "*"
bincode = "*"
bitflags = "*"
block-buffer = "*"
block-modes = "*"
brotli = "*"
bump_alloc = "*"
bumpalo = "*"
byteorder = "*"
bytes = "*"
cargo-wasm = "*"
cargo-watch = "*"
cc = "*"
cfg-if = "*"
chrono = "*"
chrono-tz = "*"
clap = "*"
config = "*"
configure_me_codegen = "*"
criterion = "*"
crossbeam-channel = "*"
crossbeam-utils = "*"
csv = "*"
ctor = "*"
cursive_core = "*"
dashmap = "*"
data-encoding = "*"
datatest-derive = "*"
derive-new = "*"
derive_more = "*"
deunicode = "*"
diesel = "*"
diesel_cli = "*"
diesel_cli_ext = "*"
digest = "*"
directories = "*"
documentation = "*"
dotenv = "*"
#easycurses = "*"
either = "*"
enumset = "*"
env_logger = "*"
error-chain = "*"
fantoccini = "*"
#fasthash = "*"
file_shred = "*"
filetime = "*"
flame = "*"
flamer = "*"
fnv = "*"
futures = "*"
futures-channel = "*"
futures-core = "*"
futures-io = "*"
futures-macro = "*"
futures-preview = "*"
futures-sink = "*"
futures-task = "*"
futures-util = "*"
generic-array = "*"
getrandom = "*"
h2 = "*"
hashbrown = "*"
heck = "*"
honggfuzz = "*"
http = "*"
http-body = "*"
human-panic = "*"
hyper = "*"
idna = "*"
image = "*"
indexmap = "*"
indicatif = "*"
indoc = "*"
instant = "*"
ipnetwork = "*"
itertools = "*"
itoa = "*"
jemallocator = "*"
jni = "*"
lalrpop = "*"
lalrpop-util = "*"
lazy_static = "*"
lazycell = "*"
leb128 = "*"
libc = "*"
lipsum = "*"
lock_api = "*"
log = "*"
mango_ir = "*"
matches = "*"
memchr = "*"
memoffset = "*"
miniz_oxide = "*"
mio = "*"
mockstream = "*"
ndarray = "*"
ndarray-linalg = "*"
ndarray-rand = "*"
nodrop = "*"
nom = "*"
num = "*"
num-complex = "*"
num-traits = "*"
num_cpus = "*"
number2name = "*"
once_cell = "*"
opaque-debug = "*"
openssl = "*"
owning_ref = "*"
parity-wasm = "*"
parking_lot = "*"
parking_lot_core = "*"
pathdiff = "*"
percent-encoding = "*"
petgraph = "*"
pin-project-lite = "*"
pin-utils = "*"
ppv-lite86 = "*"
pretty_env_logger = "*"
proc-macro-hack = "*"
proc-macro2 = "*"
protobuf = "*"
protoc-rust = "*"
quote = "*"
rand = "*"
rand_chacha = "*"
rand_core = "*"
rand_hc = "*"
rand_xorshift = "*"
rayon = "*"
redox_syscall = "*"
regex = "*"
regex-syntax = "*"
region = "*"
ring = "*"
rmp-serde = "*"
rpassword = "*"
rustc-demangle = "*"
rustc_version = "*"
rusty-fork = "*"
ryu = "*"
schemafy = "*"
schemafy_core = "*"
scoped-pool = "*"
scoped_name = "*"
scopeguard = "*"
secstr = "*"
semver = "*"
semver-parser = "*"
separator = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
serde_yaml = "*"
sha2 = "*"
signal-hook = "*"
signal-hook-mio = "*"
#simd-json = "*"
simple-server = "*"
slab = "*"
smallvec = "*"
socket2 = "*"
spin = "*"
static_assertions = "*"
stdweb = "*"
string-interner = "*"
string_cache = "*"
strsim = "*"
structopt = "*"
syn = "*"
tempfile = "*"
textwrap = "*"
thiserror = "*"
thiserror-impl = "*"
thread-id = "*"
thread_local = "*"
time = "*"
tinyvec = "*"
tokio = "*"
tokio-tungstenite = "*"
toml = "*"
tracing = "*"
tracing-core = "*"
tungstenite = "*"
twofish = "*"
twox-hash = "*"
typenum = "*"
ucd-util = "*"
unicase = "*"
unicode-bidi = "*"
unicode-normalization = "*"
unicode-segmentation = "*"
unicode-width = "*"
unicode-xid = "*"
url = "*"
ustr = "*"
utf8-ranges = "*"
version_check = "*"
walkdir = "*"
wasm-bindgen = "*"
wasm-bindgen-test = "*"
winapi = "*"
ws = "*"
yaml-rust = "*"
zxcvbn = "*"

[profile.dev.package."*"]
opt-level = 3
