
name: 'Rust nightly musl base'

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Release Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
